# exam_data.py — All exam questions

EXAMS = {

"psc_1": {
    "title": "Present Simple vs Continuous — Exam 1",
    "instruction": "Choose between Present Simple and Present Continuous.",
    "questions": [
        {"q": "1. You can't see Jimmy now. He ___ a bath.", "answer": "is having", "hint": "(HAVE)"},
        {"q": "2. He ___ to the theatre.", "answer": "never goes", "hint": "(NEVER GO)"},
        {"q": "3. Anne ___ all her clothes herself.", "answer": "makes", "hint": "(MAKE)"},
        {"q": "4. At the moment she ___ a dress for a fancy dress party.", "answer": "is making", "hint": "(MAKE)"},
        {"q": "5. He usually ___ coffee for breakfast.", "answer": "has", "hint": "(HAVE)"},
        {"q": "6. But today he ___ tea.", "answer": "is having", "hint": "(HAVE)"},
        {"q": "7. I can't go home now because it ___.", "answer": "is raining", "hint": "(RAIN)"},
        {"q": "8. I ___ an umbrella.", "answer": "don't have", "hint": "(NOT HAVE)"},
        {"q": "9. In Britain women normally ___ hats.", "answer": "don't wear", "hint": "(NOT WEAR)"},
        {"q": "10. The sun ___ in the east.", "answer": "rises", "hint": "(RISE)"},
        {"q": "11. The sun ___ in the west.", "answer": "sets", "hint": "(SET)"},
        {"q": "12. Who ___ that terrible noise outside?", "answer": "is making", "hint": "(MAKE)"},
        {"q": "13. It's Dad. He ___ the lawn.", "answer": "is mowing", "hint": "(MOW)"},
        {"q": "14. I ___ this weekend near the coast.", "answer": "am spending", "hint": "(SPEND)"},
        {"q": "15. I ___ there nearly every weekend.", "answer": "go", "hint": "(GO)"},
        {"q": "16. She ___ thirty cigarettes a day.", "answer": "smokes", "hint": "(SMOKE)"},
        {"q": "17. At the moment she ___ to stop.", "answer": "is trying", "hint": "(TRY)"},
        {"q": "18. Something ___ in the kitchen.", "answer": "is burning", "hint": "(BURN)"},
        {"q": "19. He always ___ his bills on time.", "answer": "pays", "hint": "(PAY)"},
        {"q": "20. The plane that ___ Heathrow at 9.15 is on schedule.", "answer": "leaves", "hint": "(LEAVE)"},
    ],
},
"psc_2": {
    "title": "Present Simple vs Continuous — Exam 2",
    "instruction": "Choose between Present Simple and Present Continuous.",
    "questions": [
        {"q": "1. ___ how old I am?", "answer": "do you know", "hint": "(YOU KNOW)"},
        {"q": "2. How ___ to work?", "answer": "do you get", "hint": "(YOU GET)"},
        {"q": "3. I usually ___ by car.", "answer": "drive", "hint": "(DRIVE)"},
        {"q": "4. Today Jack ___ me up.", "answer": "is picking", "hint": "(PICK)"},
        {"q": "5. It often ___ in Ireland.", "answer": "rains", "hint": "(RAIN)"},
        {"q": "6. Jane's husband ___.", "answer": "doesn't smoke", "hint": "(NOT SMOKE)"},
        {"q": "7. Why ___ on your coat?", "answer": "are you putting", "hint": "(YOU PUT)"},
        {"q": "8. I always ___ lottery tickets.", "answer": "buy", "hint": "(BUY)"},
        {"q": "9. It ___ in Egypt.", "answer": "doesn't often rain", "hint": "(NOT OFTEN RAIN)"},
        {"q": "10. The car ___ such a strange noise.", "answer": "is making", "hint": "(MAKE)"},
        {"q": "11. It always ___ like that.", "answer": "sounds", "hint": "(SOUND)"},
        {"q": "12. Susan ___ to her parents every Sunday.", "answer": "writes", "hint": "(WRITE)"},
        {"q": "13. In fact, she ___ to them today.", "answer": "is writing", "hint": "(WRITE)"},
        {"q": "14. She normally ___ in London.", "answer": "lives", "hint": "(LIVE)"},
        {"q": "15. This weekend she ___ with some friends in Liverpool.", "answer": "is staying", "hint": "(STAY)"},
        {"q": "16. Hurry up, the teacher ___ to begin!", "answer": "is waiting", "hint": "(WAIT)"},
        {"q": "17. I ___ a word he ___.", "answer": "don't believe / says", "hint": "(NOT BELIEVE, SAY)"},
        {"q": "18. What ___ for a living, Claire?", "answer": "do you do", "hint": "(YOU DO)"},
        {"q": "19. Look over there! He ___ in a non-smoking area!", "answer": "is smoking", "hint": "(SMOKE)"},
        {"q": "20. Stop! You ___ the flowers every time the ball ___ in the garden!", "answer": "destroy / lands", "hint": "(DESTROY, LAND)"},
    ],
},
"psc_3": {
    "title": "Present Simple vs Continuous — Exam 3",
    "instruction": "Choose between Present Simple and Present Continuous.",
    "questions": [
        {"q": "1. We ___ our break now, Mr. Miller.", "answer": "are taking", "hint": "(TAKE)"},
        {"q": "2. She ___ for Liverpool later in the day.", "answer": "is leaving", "hint": "(LEAVE)"},
        {"q": "3. The actor usually ___ a lot of fan mail.", "answer": "gets", "hint": "(GET)"},
        {"q": "4. The car ___ oil. Can you repair it?", "answer": "is losing", "hint": "(LOSE)"},
        {"q": "5. Dorothy ___ reading good books during her holidays.", "answer": "loves", "hint": "(LOVE)"},
        {"q": "6. My brother ___ Italy at the moment.", "answer": "is touring", "hint": "(TOUR)"},
        {"q": "7. They ___ a game of cards right now.", "answer": "are having", "hint": "(HAVE)"},
        {"q": "8. I ___ a hat today because there's a very special event.", "answer": "am wearing", "hint": "(WEAR)"},
        {"q": "9. Such bad behaviour always ___ me mad.", "answer": "makes", "hint": "(MAKE)"},
        {"q": "10. Unpopular songs ___ very well.", "answer": "don't sell", "hint": "(NOT SELL)"},
        {"q": "11. She usually ___ out with her friends on Saturday evenings.", "answer": "goes", "hint": "(GO)"},
        {"q": "12. What ___, Mum?", "answer": "are you baking", "hint": "(YOU BAKE)"},
        {"q": "13. ___ to the bridge club?", "answer": "do you belong", "hint": "(YOU BELONG)"},
        {"q": "14. The children ___ playing in the hut whenever we're at our weekend house.", "answer": "enjoy", "hint": "(ENJOY)"},
        {"q": "15. The headmaster rarely ___ a class.", "answer": "teaches", "hint": "(TEACH)"},
        {"q": "16. He normally ___ administrative work.", "answer": "does", "hint": "(DO)"},
        {"q": "17. ___ if I ask you a question?", "answer": "do you mind", "hint": "(YOU MIND)"},
        {"q": "18. I ___ some money because I want to travel to Spain.", "answer": "am currently saving", "hint": "(CURRENTLY SAVE)"},
        {"q": "19. What ___?", "answer": "does this book cost", "hint": "(THIS BOOK - COST)"},
        {"q": "20. Robert ___ to catch the same bus every morning.", "answer": "tries", "hint": "(TRY)"},
    ],
},
"psc_4": {
    "title": "Present Simple vs Continuous — Exam 4",
    "instruction": "Choose between Present Simple and Present Continuous.",
    "questions": [
        {"q": "1. It often ___ in Ireland, but it ___ there at the moment.", "answer": "rains / is not raining", "hint": "(RAIN, NOT RAIN)"},
        {"q": "2. Such behaviour normally ___ me furious.", "answer": "makes", "hint": "(MAKE)"},
        {"q": "3. I ___ a word he says.", "answer": "don't believe", "hint": "(NOT BELIEVE)"},
        {"q": "4. I ___ a hat today because it's such a special event.", "answer": "am wearing", "hint": "(WEAR)"},
        {"q": "5. Susan ___ an email to her parents nearly every Saturday evening.", "answer": "writes", "hint": "(WRITE)"},
        {"q": "6. You ___ the flowers every time the ball ___ in the flower bed.", "answer": "break / lands", "hint": "(BREAK, LAND)"},
        {"q": "7. I ___ he ___ tennis with his younger brother.", "answer": "think / is playing", "hint": "(THINK, PLAY)"},
        {"q": "8. My mum ___ a party for her best friends once a year.", "answer": "organises", "hint": "(ORGANISE)"},
        {"q": "9. She ___ in London, but she ___ with friends in Scotland.", "answer": "lives / is currently staying", "hint": "(LIVE, CURRENTLY STAY)"},
        {"q": "10. Our headmaster rarely ___ a class.", "answer": "teaches", "hint": "(TEACH)"},
        {"q": "11. Look at her! She ___ in a non-smoking area.", "answer": "is smoking", "hint": "(SMOKE)"},
        {"q": "12. ___ to a tennis club?", "answer": "do you belong", "hint": "(YOU BELONG)"},
        {"q": "13. Dana ___ reading a good novel.", "answer": "loves", "hint": "(LOVE)"},
        {"q": "14. Songs that are not very popular ___ very well.", "answer": "don't sell", "hint": "(NOT SELL)"},
        {"q": "15. My brother isn't here. He ___ Spain at the moment.", "answer": "is touring", "hint": "(TOUR)"},
        {"q": "16. Tom always ___ the strangest questions in class.", "answer": "asks", "hint": "(ASK)"},
        {"q": "17. I ___ lottery tickets every week, but I ___ anything.", "answer": "buy / never win", "hint": "(BUY, NEVER WIN)"},
        {"q": "18. You can't disturb them. They ___ a game of cards.", "answer": "are playing", "hint": "(PLAY)"},
        {"q": "19. I ___ websites for a living.", "answer": "create", "hint": "(CREATE)"},
        {"q": "20. She ___ of leaving home and going to Australia for a year.", "answer": "is thinking", "hint": "(THINK)"},
    ],
},
"psc_5": {
    "title": "Present Simple vs Continuous — Exam 5",
    "instruction": "Choose between Present Simple and Present Continuous.",
    "questions": [
        {"q": "1. They normally ___ a coffee break at ten, but today they ___ one.", "answer": "have / aren't having", "hint": "(HAVE, NOT HAVE)"},
        {"q": "2. Why ___ my coat?", "answer": "are you wearing", "hint": "(YOU WEAR)"},
        {"q": "3. It ___ just like mine.", "answer": "looks", "hint": "(LOOK)"},
        {"q": "4. The food ___ chemicals that make it last longer.", "answer": "contains", "hint": "(CONTAIN)"},
        {"q": "5. It ___ the moon about 28 days to travel around the earth.", "answer": "takes", "hint": "(TAKE)"},
        {"q": "6. Everything in this box ___ to my grandfather.", "answer": "belongs", "hint": "(BELONG)"},
        {"q": "7. He ___ it to me instead of my brother.", "answer": "is giving", "hint": "(GIVE)"},
        {"q": "8. Mary ___ through a very difficult period at university this year.", "answer": "is going", "hint": "(GO)"},
        {"q": "9. Dad ___ everything about airplanes.", "answer": "knows", "hint": "(KNOW)"},
        {"q": "10. He always ___ books about aviation.", "answer": "reads", "hint": "(READ)"},
        {"q": "11. I used to play football but now I ___ rugby.", "answer": "prefer", "hint": "(PREFER)"},
        {"q": "12. What ___ to do this evening?", "answer": "are you planning", "hint": "(YOU PLAN)"},
        {"q": "13. Well, I ___ to a concert with a few friends.", "answer": "am going", "hint": "(GO)"},
        {"q": "14. What ___ for a living?", "answer": "does your dad do", "hint": "(YOUR DAD DO)"},
        {"q": "15. At the moment he ___ for a new job.", "answer": "is looking", "hint": "(LOOK)"},
        {"q": "16. You ___ shopping every Saturday.", "answer": "go", "hint": "(GO)"},
        {"q": "17. I ___ absolutely no idea what this movie is about.", "answer": "have", "hint": "(HAVE)"},
        {"q": "18. The two department managers ___ lunch at the moment.", "answer": "are having", "hint": "(HAVE)"},
        {"q": "19. Teachers ___ us homework every day.", "answer": "give", "hint": "(GIVE)"},
        {"q": "20. The air ___ strange.", "answer": "smells", "hint": "(SMELL)"},
    ],
},
"psc_6": {
    "title": "Present Simple vs Continuous — Exam 6",
    "instruction": "Choose between Present Simple and Present Continuous.",
    "questions": [
        {"q": "1. Dad ___ us to school every morning.", "answer": "drives", "hint": "(DRIVE)"},
        {"q": "2. Max ___ at an Internet cafe this summer.", "answer": "is working", "hint": "(WORK)"},
        {"q": "3. We ___ abroad this year because of the pandemic.", "answer": "are not going", "hint": "(NOT GO)"},
        {"q": "4. It never ___ in the Atacama Desert in Chile.", "answer": "rains", "hint": "(RAIN)"},
        {"q": "5. Marty ___ to the fitness centre on Mondays.", "answer": "does not usually go", "hint": "(NOT USUALLY GO)"},
        {"q": "6. I ___ sounds that are not there.", "answer": "am hearing", "hint": "(HEAR)"},
        {"q": "7. We ___ of leaving Britain next year.", "answer": "are thinking", "hint": "(THINK)"},
        {"q": "8. I ___ my ex-husband next Monday.", "answer": "am seeing", "hint": "(SEE)"},
        {"q": "9. This box ___ a lot. What is in it?", "answer": "weighs", "hint": "(WEIGH)"},
        {"q": "10. What ___ under the table?", "answer": "are you doing", "hint": "(YOU DO)"},
        {"q": "11. She never ___ to anyone about her problems.", "answer": "talks", "hint": "(TALK)"},
        {"q": "12. Mary ___ very sad. What has happened to her?", "answer": "looks", "hint": "(LOOK)"},
        {"q": "13. They ___ a few days in Stockholm next month.", "answer": "are spending", "hint": "(SPEND)"},
        {"q": "14. You can't go in. They ___ a meeting.", "answer": "are having", "hint": "(HAVE)"},
        {"q": "15. I ___ I'll have a cup of coffee.", "answer": "think", "hint": "(THINK)"},
        {"q": "16. ___ fishing with me on Sunday?", "answer": "are you going", "hint": "(YOU GO)"},
        {"q": "17. I ___ here as a waiter on weekends.", "answer": "work", "hint": "(WORK)"},
        {"q": "18. I ___ what this letter means. It ___ no sense.", "answer": "don't understand / makes", "hint": "(NOT UNDERSTAND, MAKE)"},
        {"q": "19. I ___ the dog for a walk because it's so sunny outside.", "answer": "am taking", "hint": "(TAKE)"},
        {"q": "20. I ___ meat. I'm a vegetarian.", "answer": "don't eat", "hint": "(NOT EAT)"},
    ],
},
"ppc_1": {
    "title": "Present Perfect Simple vs Continuous — Exam 1",
    "instruction": "Choose between Present Perfect Simple and Present Perfect Continuous.",
    "questions": [
        {"q": "1. I ___ several books about sailing.", "answer": "have been reading / have read", "hint": "(READ)"},
        {"q": "2. You look exhausted. What ___?", "answer": "have you been doing", "hint": "(YOU DO)"},
        {"q": "3. He ___ that book for over two weeks.", "answer": "has been reading", "hint": "(READ)"},
        {"q": "4. He ___ yet. He's such a slow reader.", "answer": "hasn't finished", "hint": "(NOT FINISH)"},
        {"q": "5. My sister ___ in Norwich for two months.", "answer": "has been living", "hint": "(LIVE)"},
        {"q": "6. My dad ___ a new job.", "answer": "has just started", "hint": "(JUST START)"},
        {"q": "7. It ___ for several days now.", "answer": "has been raining", "hint": "(RAIN)"},
        {"q": "8. ___ your homework yet?", "answer": "have you finished", "hint": "(YOU FINISH)"},
        {"q": "9. You ___ on it for hours.", "answer": "have been working", "hint": "(WORK)"},
        {"q": "10. Maria ___ for a job since she left school.", "answer": "has been looking", "hint": "(LOOK)"},
        {"q": "11. She still ___ one.", "answer": "hasn't found", "hint": "(NOT FIND)"},
        {"q": "12. They ___ TV the whole evening.", "answer": "have been watching", "hint": "(WATCH)"},
        {"q": "13. It's their favourite film and they ___ it several times.", "answer": "have seen", "hint": "(SEE)"},
        {"q": "14. I ___ him about his new girlfriend twice this week.", "answer": "have asked", "hint": "(ASK)"},
        {"q": "15. I ___ my driving test.", "answer": "have just passed", "hint": "(JUST PASS)"},
        {"q": "16. I ___ ill lately.", "answer": "have been", "hint": "(BE)"},
        {"q": "17. We ___ the date for the marriage.", "answer": "have set", "hint": "(SET)"},
        {"q": "18. I ___ him for ages.", "answer": "haven't seen", "hint": "(NOT SEE)"},
    ],
},
"ppc_2": {
    "title": "Present Perfect Simple vs Continuous — Exam 2",
    "instruction": "Choose between Present Perfect Simple and Present Perfect Continuous.",
    "questions": [
        {"q": "1. I ___ the book you gave me.", "answer": "have read", "hint": "(READ)"},
        {"q": "2. You ___ too hard lately.", "answer": "have probably been working", "hint": "(PROBABLY WORK)"},
        {"q": "3. Rachel ___ around Europe for two months now.", "answer": "has been travelling", "hint": "(TRAVEL)"},
        {"q": "4. She ___ six countries so far.", "answer": "has visited", "hint": "(VISIT)"},
        {"q": "5. It ___ but the streets are still wet.", "answer": "has already stopped", "hint": "(ALREADY STOP)"},
        {"q": "6. I ___ at your report for some time.", "answer": "have been looking", "hint": "(LOOK)"},
        {"q": "7. James ___ the new Harry Potter novel for hours now.", "answer": "has been reading", "hint": "(READ)"},
        {"q": "8. I ___ this few times, but I'll say it again.", "answer": "have already said", "hint": "(ALREADY SAY)"},
        {"q": "9. The two brothers ___ films since they left high school.", "answer": "have been making", "hint": "(MAKE)"},
        {"q": "10. Look! Someone ___ that window!", "answer": "has broken", "hint": "(BREAK)"},
        {"q": "11. I ___ to him, but he ___ me an answer yet.", "answer": "have already written / hasn't given", "hint": "(ALREADY WRITE, NOT GIVE)"},
        {"q": "12. You are too late. The patient ___.", "answer": "has just died", "hint": "(JUST DIE)"},
        {"q": "13. Where ___?", "answer": "has he gone", "hint": "(HE GO)"},
        {"q": "14. They ___ from New York.", "answer": "have just arrived", "hint": "(JUST ARRIVE)"},
        {"q": "15. Mr Benson ___ the whole morning.", "answer": "has been fishing", "hint": "(FISH)"},
        {"q": "16. So far, he ___ three fish.", "answer": "has caught", "hint": "(CATCH)"},
        {"q": "17. She ___ Charles since she was 17.", "answer": "has known", "hint": "(KNOW)"},
        {"q": "18. John ___ off his bike again.", "answer": "has fallen", "hint": "(FALL)"},
    ],
},
"ppc_3": {
    "title": "Present Perfect Simple vs Continuous — Exam 3",
    "instruction": "Choose between Present Perfect Simple and Present Perfect Continuous.",
    "questions": [
        {"q": "1. I'm so tired because I ___ so hard lately.", "answer": "have been working", "hint": "(WORK)"},
        {"q": "2. The new midfielder ___ 5 goals so far this season.", "answer": "has scored", "hint": "(SCORE)"},
        {"q": "3. I ___ both bottles.", "answer": "have drunk", "hint": "(DRINK)"},
        {"q": "4. Jenifer ___ too much.", "answer": "has probably been eating", "hint": "(PROBABLY EAT)"},
        {"q": "5. I ___ a new pair of shoes. How do you like them?", "answer": "have just bought", "hint": "(JUST BUY)"},
        {"q": "6. ___ reading the newspaper?", "answer": "have you finished", "hint": "(YOU FINISH)"},
        {"q": "7. So far, I ___ the introduction.", "answer": "have only written", "hint": "(ONLY WRITE)"},
        {"q": "8. Look at how she's sweating. She ___ for hours.", "answer": "has probably been running", "hint": "(PROBABLY RUN)"},
        {"q": "9. How long ___ Russian?", "answer": "have you been learning", "hint": "(YOU LEARN)"},
        {"q": "10. You ___ computer games ever since you got up.", "answer": "have been playing", "hint": "(PLAY)"},
        {"q": "11. My sister ___ with her roommate for 5 years.", "answer": "has been living", "hint": "(LIVE)"},
        {"q": "12. I ___ for it for hours and ___ it yet.", "answer": "have been looking / haven't found", "hint": "(LOOK, NOT FIND)"},
        {"q": "13. What ___ up to now?", "answer": "have you been doing", "hint": "(YOU DO)"},
        {"q": "14. I ___ a new job and I can start next Wednesday.", "answer": "have found", "hint": "(FIND)"},
        {"q": "15. I ___ Patricia since we were in kindergarten together.", "answer": "haven't seen", "hint": "(NOT SEE)"},
        {"q": "16. I ___ all my passwords recently.", "answer": "have changed", "hint": "(CHANGE)"},
        {"q": "17. I ___ the new Schwarzenegger film.", "answer": "have already seen", "hint": "(ALREADY SEE)"},
        {"q": "18. Dad ___ since he was in high school.", "answer": "hasn't danced", "hint": "(DANCE)"},
    ],
},
"ppc_4": {
    "title": "Present Perfect Simple vs Continuous — Exam 4",
    "instruction": "Choose between Present Perfect Simple and Present Perfect Continuous.",
    "questions": [
        {"q": "1. The solar system ___ for billions of years.", "answer": "has existed", "hint": "(EXIST)"},
        {"q": "2. They ___ in California for the last 20 years.", "answer": "have been living", "hint": "(LIVE)"},
        {"q": "3. I'm so tired. I ___ well in the last few days.", "answer": "haven't been feeling", "hint": "(NOT FEEL)"},
        {"q": "4. The eastern European countries ___ members of the EU for the last 15 years.", "answer": "have been", "hint": "(BE)"},
        {"q": "5. ___ on an interesting project lately?", "answer": "have you been working", "hint": "(YOU WORK)"},
        {"q": "6. She ___ to a few specialists, but they can't help her.", "answer": "has gone", "hint": "(GO)"},
        {"q": "7. I ___ problems with my car recently.", "answer": "have been having", "hint": "(HAVE)"},
        {"q": "8. The mechanic ___ the faulty part yet.", "answer": "hasn't found", "hint": "(NOT FIND)"},
        {"q": "9. We ___ cards for the last few hours.", "answer": "have been playing", "hint": "(PLAY)"},
        {"q": "10. ___ an important title?", "answer": "has the team ever won", "hint": "(THE TEAM, EVER, WIN)"},
        {"q": "11. It ___ hard for the last three hours.", "answer": "has been raining", "hint": "(RAIN)"},
        {"q": "12. Some roads ___ impassable.", "answer": "have become", "hint": "(BECOME)"},
        {"q": "13. My parents ___ me.", "answer": "have always understood", "hint": "(ALWAYS UNDERSTAND)"},
        {"q": "14. Where ___ the money?", "answer": "have you hidden", "hint": "(YOU HIDE)"},
        {"q": "15. A big earthquake ___ the area since the beginning of the century.", "answer": "hasn't hit", "hint": "(NOT HIT)"},
        {"q": "16. I ___ four emails this morning, but nobody ___.", "answer": "have written / has replied", "hint": "(WRITE, REPLY)"},
        {"q": "17. The bank is still closed. It ___ yet.", "answer": "hasn't opened", "hint": "(NOT OPEN)"},
        {"q": "18. I ___ the baby twice already but it's still hungry.", "answer": "have fed", "hint": "(FEED)"},
    ],
},
"ppc_5": {
    "title": "Present Perfect Simple vs Continuous — Exam 5",
    "instruction": "Choose between Present Perfect Simple and Present Perfect Continuous.",
    "questions": [
        {"q": "1. I ___ an interesting article in the New York Times.", "answer": "have just read", "hint": "(JUST READ)"},
        {"q": "2. ___ by a dog?", "answer": "have you ever been bitten", "hint": "(YOU EVER BITE)"},
        {"q": "3. A bee ___ me recently.", "answer": "has stung", "hint": "(STING)"},
        {"q": "4. You ___ hard enough.", "answer": "haven't worked / haven't been working", "hint": "(NOT WORK)"},
        {"q": "5. That's why you ___ a few mistakes in the last few days.", "answer": "have made", "hint": "(MAKE)"},
        {"q": "6. The Johnsons ___ in Park Street for over a decade.", "answer": "have been living", "hint": "(LIVE)"},
        {"q": "7. They ___ about leaving.", "answer": "have never thought", "hint": "(NEVER THINK)"},
        {"q": "8. We ___ a lot about climate change since I came here.", "answer": "have learned", "hint": "(LEARN)"},
        {"q": "9. I ___ 3 great days with my new boyfriend.", "answer": "have spent", "hint": "(SPEND)"},
        {"q": "10. Who ___ after the children recently?", "answer": "has been looking", "hint": "(LOOK)"},
        {"q": "11. How long ___ each other?", "answer": "have you known", "hint": "(YOU KNOW)"},
        {"q": "12. We ___ since then.", "answer": "have been dating", "hint": "(DATE)"},
        {"q": "13. I ___ anything since I had breakfast this morning.", "answer": "haven't eaten", "hint": "(NOT EAT)"},
        {"q": "14. What ___ in the last half hour?", "answer": "have you been doing", "hint": "(YOU DO)"},
        {"q": "15. I ___ the garage, but I ___ yet.", "answer": "have been cleaning / haven't finished", "hint": "(CLEAN, NOT FINISH)"},
        {"q": "16. Our daughter ___ in Los Angeles for two years.", "answer": "has been studying", "hint": "(STUDY)"},
        {"q": "17. The crowd ___ since the home team scored.", "answer": "has been cheering", "hint": "(CHEER)"},
        {"q": "18. I ___ about going abroad lately.", "answer": "have been thinking", "hint": "(THINK)"},
    ],
},
"ppc_6": {
    "title": "Present Perfect Simple vs Continuous — Exam 6",
    "instruction": "Choose between Present Perfect Simple and Present Perfect Continuous.",
    "questions": [
        {"q": "1. I ___ on redecorating the house for the last few days.", "answer": "have been working", "hint": "(WORK)"},
        {"q": "2. She ___ his phone number, so she can't call him.", "answer": "has forgotten", "hint": "(FORGET)"},
        {"q": "3. It ___ all day.", "answer": "has been raining", "hint": "(RAIN)"},
        {"q": "4. I ___ a lot of work this morning, and it's only nine.", "answer": "have done", "hint": "(DO)"},
        {"q": "5. She ___ the tasks her teacher provided her with.", "answer": "has just finished", "hint": "(JUST FINISH)"},
        {"q": "6. We ___ for our exams since October.", "answer": "have been studying", "hint": "(STUDY)"},
        {"q": "7. I ___ after the children the whole morning.", "answer": "have been looking", "hint": "(LOOK)"},
        {"q": "8. We ___ this film before.", "answer": "have seen", "hint": "(SEE)"},
        {"q": "9. I ___ for you all morning.", "answer": "have been waiting", "hint": "(WAIT)"},
        {"q": "10. Mike ___ an airplane before.", "answer": "has flown", "hint": "(FLY)"},
        {"q": "11. I ___ up my mind not to accept the job offer.", "answer": "have made", "hint": "(MAKE)"},
        {"q": "12. I ___ to India twice.", "answer": "have been", "hint": "(BE)"},
        {"q": "13. Jack ___ his driving test twice.", "answer": "has failed", "hint": "(FAIL)"},
        {"q": "14. I ___ to a party since Christmas.", "answer": "haven't been", "hint": "(NOT BE)"},
        {"q": "15. People ___ all morning about slow internet services.", "answer": "have been complaining", "hint": "(COMPLAIN)"},
        {"q": "16. My brother ___ for this company for the last forty years.", "answer": "has been working", "hint": "(WORK)"},
        {"q": "17. Someone ___ my computer. The battery is dead.", "answer": "has been using", "hint": "(USE)"},
        {"q": "18. Why ___ your monthly fee yet?", "answer": "haven't you paid", "hint": "(YOU NOT PAY)"},
        {"q": "19. He ___ golf with us since he moved here.", "answer": "has been playing", "hint": "(PLAY)"},
        {"q": "20. My mother ___ the bus, so she won't be here on time.", "answer": "has missed", "hint": "(MISS)"},
        {"q": "21. I ___ three letters so far this morning.", "answer": "have typed", "hint": "(TYPE)"},
        {"q": "22. The baby ___. That's why her eyes are so red.", "answer": "has been crying", "hint": "(CRY)"},
        {"q": "23. I am really excited because I ___ Indian food before.", "answer": "have never eaten", "hint": "(NEVER EAT)"},
        {"q": "24. We ___ through the accounts since Monday.", "answer": "have been looking", "hint": "(LOOK)"},
        {"q": "25. My cousin ___ this house since the end of the war.", "answer": "has owned", "hint": "(OWN)"},
    ],
},
"ppc_7": {
    "title": "Present Perfect Simple vs Continuous — Exam 7",
    "instruction": "Choose between Present Perfect Simple and Present Perfect Continuous.",
    "questions": [
        {"q": "1. I ___ a new pair of shoes.", "answer": "have just bought", "hint": "(JUST BUY)"},
        {"q": "2. ___ that book yet?", "answer": "have you finished", "hint": "(YOU FINISH)"},
        {"q": "3. They ___ cookies all afternoon.", "answer": "have been eating", "hint": "(EAT)"},
        {"q": "4. I ___ this book now, so you can have it back.", "answer": "have read", "hint": "(READ)"},
        {"q": "5. The novelist ___ eight pages of his new book.", "answer": "has already written", "hint": "(ALREADY WRITE)"},
        {"q": "6. What ___ in the past hour?", "answer": "have you been doing", "hint": "(YOU DO)"},
        {"q": "7. My sister ___ everything I left in the kitchen.", "answer": "has eaten", "hint": "(EAT)"},
        {"q": "8. You ___ computer games ever since you had your breakfast.", "answer": "have been playing", "hint": "(PLAY)"},
        {"q": "9. I ___ you for ages! You look fantastic!", "answer": "haven't seen", "hint": "(NOT SEE)"},
        {"q": "10. Lukaku ___ another goal for Manchester United.", "answer": "has just scored", "hint": "(JUST SCORE)"},
        {"q": "11. They ___ for over an hour now.", "answer": "have been dancing", "hint": "(DANCE)"},
        {"q": "12. We ___ for you for ages.", "answer": "have been waiting", "hint": "(WAIT)"},
        {"q": "13. I ___ my work, so I'm ready to go.", "answer": "have finished", "hint": "(FINISH)"},
        {"q": "14. She ___ emails for over an hour.", "answer": "has been writing", "hint": "(WRITE)"},
        {"q": "15. We ___ ten museums since we arrived here in Rome.", "answer": "have visited", "hint": "(VISIT)"},
        {"q": "16. I am very tired, because I ___ around the city all day long.", "answer": "have been travelling", "hint": "(TRAVEL)"},
        {"q": "17. She ___ for a good job for over a week.", "answer": "has been looking", "hint": "(LOOK)"},
        {"q": "18. Jane ___ English at university for over a decade.", "answer": "has been teaching", "hint": "(TEACH)"},
    ],
},
"pro_1": {
    "title": "Pronouns — Exam 1 (Indefinite Pronouns)",
    "instruction": "Fill in the blank with the correct indefinite pronoun: somebody/something/somewhere/anybody/anything/anywhere/nobody/nothing/nowhere/everybody/everything/everywhere.",
    "questions": [
        {"q": "1. She wants to live ___ by the sea.", "answer": "somewhere", "hint": ""},
        {"q": "2. She put ___ in the box, all the things that she had.", "answer": "everything", "hint": ""},
        {"q": "3. Does ___ have a phone charger?", "answer": "anybody", "hint": ""},
        {"q": "4. We went ___ this weekend. We stayed at home.", "answer": "nowhere", "hint": ""},
        {"q": "5. She didn't bring ___ to the party.", "answer": "anything", "hint": ""},
        {"q": "6. Is there ___ in the room?", "answer": "anything", "hint": ""},
        {"q": "7. A: What's wrong? B: ___, I'm fine.", "answer": "nothing", "hint": ""},
        {"q": "8. ___ lives in that house. It's empty.", "answer": "nobody", "hint": ""},
        {"q": "9. Would you like to go ___ this weekend?", "answer": "anywhere", "hint": ""},
        {"q": "10. ___ was really friendly, all the managers and even the CEO.", "answer": "everybody", "hint": ""},
        {"q": "11. ___ is going really well and so I'm really happy.", "answer": "everything", "hint": ""},
        {"q": "12. I know ___ in this company. It's my first day.", "answer": "nobody", "hint": ""},
        {"q": "13. Did you go ___ during the summer?", "answer": "anywhere", "hint": ""},
        {"q": "14. She doesn't want ___ to help her.", "answer": "anybody", "hint": ""},
        {"q": "15. She loves ___. She's a really kind person.", "answer": "everybody", "hint": ""},
        {"q": "16. I must have left my keys ___!", "answer": "somewhere", "hint": ""},
        {"q": "17. They looked ___ for the money.", "answer": "everywhere", "hint": ""},
        {"q": "18. Would you like ___ to drink?", "answer": "something", "hint": ""},
        {"q": "19. ___ in the UK has hot weather today.", "answer": "nowhere", "hint": ""},
        {"q": "20. ___ unusual happened. It was a very ordinary day.", "answer": "nothing", "hint": ""},
        {"q": "21. I gave the children ___ to eat because they were hungry.", "answer": "something", "hint": ""},
        {"q": "22. I wish ___ would clean this mess up!", "answer": "somebody", "hint": ""},
        {"q": "23. ___ came to the door earlier but I don't know who it was.", "answer": "somebody", "hint": ""},
        {"q": "24. I'd love to travel ___ all over the whole world!", "answer": "everywhere", "hint": ""},
    ],
},
"pro_2": {
    "title": "Pronouns — Exam 2 (Personal Pronouns)",
    "instruction": "Choose the correct personal pronoun or possessive to fill in the blank.",
    "questions": [
        {"q": "1. Could ___ take a message, please?", "answer": "you", "hint": "(you/her/your)"},
        {"q": "2. They showed us all ___ holiday photos last night.", "answer": "their", "hint": "(they/their/ours)"},
        {"q": "3. I'm sorry but these seats are ___.", "answer": "ours", "hint": "(my/their/ours)"},
        {"q": "4. Sandy and ___ are going to the cafe.", "answer": "I", "hint": "(I/me/her)"},
        {"q": "5. Do you want ___ to turn this off?", "answer": "me", "hint": "(I/me/my)"},
        {"q": "6. I saw your sister's paintings yesterday. ___ were very good.", "answer": "they", "hint": "(She/They/Its)"},
        {"q": "7. They've got two babies and they take ___ everywhere.", "answer": "them", "hint": "(they/their/them)"},
        {"q": "8. Let ___ help you with that.", "answer": "him", "hint": "(he/my/him)"},
        {"q": "9. They don't look like ___ brothers. (correct)", "answer": "their", "hint": "(their)"},
        {"q": "10. It's your father's idea, not ___. (correct)", "answer": "mine", "hint": "(mine)"},
        {"q": "11. Sam and ___ went to that concert. (correct)", "answer": "I", "hint": "(I)"},
        {"q": "12. I've never met ___ parents. (correct)", "answer": "your", "hint": "(your)"},
        {"q": "13. Only Paul and ___. (correct)", "answer": "me", "hint": "(me)"},
        {"q": "14. I would do anything for ___. (correct)", "answer": "him", "hint": "(him)"},
        {"q": "15. ___ is from a different shop. (correct)", "answer": "mine", "hint": "(mine)"},
        {"q": "16. Have you seen ___ project? I hope we get an A+. (correct)", "answer": "our", "hint": "(our)"},
    ],
},
"pro_3": {
    "title": "Pronouns — Exam 3 (Gap Fill)",
    "instruction": "Fill in the blank with the correct pronoun or possessive from context.",
    "questions": [
        {"q": "1. That's my brother's cup and this is ___.", "answer": "mine", "hint": "(mine)"},
        {"q": "2. My grandmother gave it to ___.", "answer": "me", "hint": "(me)"},
        {"q": "3. Good morning. Can ___ help ___?", "answer": "I / you", "hint": "(I, you)"},
        {"q": "4. Could ___ pass it to ___? I'll keep it safe.", "answer": "you / me", "hint": "(you, me)"},
        {"q": "5. That poor dog has lost one of ___ legs.", "answer": "its", "hint": "(its)"},
        {"q": "6. She gave ___ it last night.", "answer": "me", "hint": "(me)"},
        {"q": "7. ___ don't mind where ___ go but ___ doesn't like the beach.", "answer": "we / we / she", "hint": "(we, we, she)"},
        {"q": "8. ___ never lets ___ watch TV after 9 p.m.", "answer": "she / us", "hint": "(she, us)"},
        {"q": "9. Do you like ___ new car? ___ is second-hand.", "answer": "our / it", "hint": "(our, it)"},
    ],
},
"psp_1": {
    "title": "Past Simple vs Past Perfect — Exam 1",
    "instruction": "Choose between Past Simple and Past Perfect.",
    "questions": [
        {"q": "1. By the time we ___ to the stadium, the performance ___ so we missed the first two songs.", "answer": "got / had already started", "hint": "(GET, ALREADY START)"},
        {"q": "2. When we ___ in Spain the airport told us that they ___ our luggage.", "answer": "arrived / had lost", "hint": "(ARRIVE, LOSE)"},
        {"q": "3. After I ___ a large meal, I ___ to feel sick.", "answer": "had had / started", "hint": "(HAVE, START)"},
        {"q": "4. The shoes were very clean because I ___ hours cleaning them.", "answer": "had spent", "hint": "(SPEND)"},
        {"q": "5. It ___ his first trip to India. He ___ there several times before.", "answer": "was not / had been", "hint": "(NOT BE, BE)"},
        {"q": "6. My neighbour told me that she ___ a new car a month before.", "answer": "had bought", "hint": "(BUY)"},
        {"q": "7. Yesterday I ___ downtown to see Peter. I ___ him for months.", "answer": "went / hadn't met", "hint": "(GO, NOT MEET)"},
        {"q": "8. I ___ Matrix for the first time yesterday. I ___ it before.", "answer": "saw / had never seen", "hint": "(SEE, NEVER SEE)"},
        {"q": "9. She ___ him for very long when she ___ to get married.", "answer": "hadn't known / decided", "hint": "(NOT KNOW, DECIDE)"},
        {"q": "10. When he ___, the party was over. Everyone ___.", "answer": "arrived / had already left", "hint": "(ARRIVE, ALREADY LEAVE)"},
        {"q": "11. I was happy after I ___ my first lesson as an instructor.", "answer": "had finished", "hint": "(FINISH)"},
        {"q": "12. I visited the hospital where the ambulance ___ my mother.", "answer": "had taken", "hint": "(TAKE)"},
        {"q": "13. Everyone ___ the house by the time I ___ home.", "answer": "had left / came", "hint": "(LEAVE, COME)"},
        {"q": "14. As soon as he ___ the old clock it ___ again.", "answer": "had repaired / broke", "hint": "(REPAIR, BREAK)"},
        {"q": "15. I ___ a new car because my old one ___.", "answer": "bought / had been stolen", "hint": "(BUY, BE STEAL)"},
        {"q": "16. The teacher asked me why I ___ my homework.", "answer": "had not done", "hint": "(NOT DO)"},
    ],
},
"psp_2": {
    "title": "Past Simple vs Past Perfect — Exam 2",
    "instruction": "Choose between Past Simple, Past Perfect Simple or Past Perfect Continuous.",
    "questions": [
        {"q": "1. We were all happy because we ___ in our homework in time.", "answer": "had handed", "hint": "(HAND)"},
        {"q": "2. Mrs Shilton ___ a primary school teacher for twenty years before she became headmaster.", "answer": "had been", "hint": "(BE)"},
        {"q": "3. When we got there, we saw that they ___ for over 20 minutes.", "answer": "had been resting", "hint": "(REST)"},
        {"q": "4. We ___ dance moves for over two hours, so we were very tired.", "answer": "had been practicing", "hint": "(PRACTICE)"},
        {"q": "5. The film ___ when we finally got to the cinema.", "answer": "had already started", "hint": "(ALREADY START)"},
        {"q": "6. By the time I ___ to school the lesson had already started.", "answer": "got", "hint": "(GET)"},
        {"q": "7. I ___ up for a few minutes when the doorbell rang.", "answer": "had only been washing", "hint": "(ONLY WASH)"},
        {"q": "8. He ___ about the accident before he saw it on TV.", "answer": "had heard", "hint": "(HEAR)"},
        {"q": "9. I ___ the office after I had finished writing my last email.", "answer": "left", "hint": "(LEAVE)"},
        {"q": "10. The car ___ down shortly after we had got on the motorway.", "answer": "broke", "hint": "(BREAK)"},
        {"q": "11. We ___ for an hour when we finally arrived at the remote village.", "answer": "had been walking", "hint": "(WALK)"},
        {"q": "12. I saw the film after I ___ the book.", "answer": "had read", "hint": "(READ)"},
        {"q": "13. I ___ already thought of that before you ___ it up.", "answer": "had / brought", "hint": "(BRING)"},
        {"q": "14. She was so tired because she ___ football the whole afternoon.", "answer": "had been playing", "hint": "(PLAY)"},
        {"q": "15. As soon as the girls had cleaned the house the visitors ___.", "answer": "arrived", "hint": "(ARRIVE)"},
        {"q": "16. By the time I was 16 I ___ to become a scientist.", "answer": "had already decided", "hint": "(ALREADY DECIDE)"},
        {"q": "17. Suddenly I realised that I ___ at the wrong person.", "answer": "had been shouting", "hint": "(SHOUT)"},
        {"q": "18. I ___ from my job because I had received an offer from another company.", "answer": "resigned", "hint": "(RESIGN)"},
        {"q": "19. The teacher gave us a break because we ___ on the project for several hours.", "answer": "had been working", "hint": "(WORK)"},
        {"q": "20. After dad had finished mowing the lawn, he ___ repairing the car.", "answer": "started", "hint": "(START)"},
    ],
},
"psp_3": {
    "title": "Past Simple vs Past Perfect — Exam 3",
    "instruction": "Choose between Past Simple, Past Perfect Simple or Past Perfect Continuous.",
    "questions": [
        {"q": "1. After I ___ the letter, I ___ that I ___ the wrong address on it.", "answer": "had posted / realised / had written", "hint": "(POST, REALISE, WRITE)"},
        {"q": "2. John asked me where I ___ the day before.", "answer": "had been", "hint": "(BE)"},
        {"q": "3. At this time yesterday, we ___ for 6 km.", "answer": "had already been walking", "hint": "(ALREADY WALK)"},
        {"q": "4. When I ___ through the streets of Madrid, I ___ about the time I ___ there.", "answer": "was walking / thought / had spent", "hint": "(WALK, THINK, SPEND)"},
        {"q": "5. It was the first time that she ___ me to dinner.", "answer": "had invited", "hint": "(INVITE)"},
        {"q": "6. As soon as the maid ___ scrubbing the floor, she ___ working in the garden.", "answer": "had finished / started", "hint": "(FINISH, START)"},
        {"q": "7. We started to worry about Jimmy because we ___ him all afternoon.", "answer": "had been calling", "hint": "(CALL)"},
        {"q": "8. They ___ their way out of town before the sun ___.", "answer": "had already made / rose", "hint": "(ALREADY MAKE, RISE)"},
        {"q": "9. We ___ for two hours when we finally got to our hotel.", "answer": "had been driving", "hint": "(DRIVE)"},
        {"q": "10. When I ___ home, I saw that the children ___.", "answer": "arrived / had left", "hint": "(ARRIVE, LEAVE)"},
        {"q": "11. While I ___ in the garden it ___ me that I ___ off the oven.", "answer": "was working / struck / hadn't turned", "hint": "(WORK, STRIKE, NOT TURN)"},
        {"q": "12. I ___ my best friend to the party, but he couldn't come because he ___ other plans.", "answer": "invited / had already made", "hint": "(INVITE, ALREADY MAKE)"},
        {"q": "13. I ___ out of the window because I ___ I ___ some noises.", "answer": "looked / thought / had heard", "hint": "(LOOK, THINK, HEAR)"},
        {"q": "14. We ___ TV when we saw that a devastating earthquake ___ California.", "answer": "were watching / had hit", "hint": "(WATCH, HIT)"},
        {"q": "15. The police told me that someone ___ into our neighbour's house.", "answer": "had broken", "hint": "(BREAK)"},
        {"q": "16. When I finally ___ at the airport, he told me that he ___ for half an hour.", "answer": "arrived / had been waiting", "hint": "(ARRIVE, WAIT)"},
        {"q": "17. Patricia ___ English for three years when she ___ and ___ a job.", "answer": "had been studying / quit / got", "hint": "(STUDY, QUIT, GET)"},
        {"q": "18. We ___ to China because our flight ___.", "answer": "didn't go / had been cancelled", "hint": "(NOT GO, CANCEL)"},
    ],
},
"psp_4": {
    "title": "Past Simple vs Past Perfect — Exam 4",
    "instruction": "Choose between Past Simple, Past Perfect Simple or Past Perfect Continuous.",
    "questions": [
        {"q": "1. My friend Tim ___ well yesterday because he ___ too many sweets.", "answer": "didn't feel / had eaten", "hint": "(NOT FEEL, EAT)"},
        {"q": "2. After she ___, she ___ much better.", "answer": "had rested / felt", "hint": "(REST, FEEL)"},
        {"q": "3. She ___ him for a year before they finally ___ on holidays together.", "answer": "had known / went", "hint": "(KNOW, GO)"},
        {"q": "4. I asked him what ___ because I ___ noise the whole morning.", "answer": "had happened / had been hearing", "hint": "(HAPPEN, HEAR)"},
        {"q": "5. The next morning, I realised that someone ___ my new bike.", "answer": "had stolen", "hint": "(STEAL)"},
        {"q": "6. I ___ to the meeting last Monday because nobody ___ me.", "answer": "didn't go / had invited", "hint": "(NOT GO, INVITE)"},
        {"q": "7. Dan was so excited because he ___ 1,000 euros in the lottery.", "answer": "had just won", "hint": "(JUST WIN)"},
        {"q": "8. After she ___ her first major tournament, she ___ from a series of injuries.", "answer": "had won / suffered", "hint": "(WIN, SUFFER)"},
        {"q": "9. Our manager told us that the company ___ bankrupt.", "answer": "had gone", "hint": "(GO)"},
        {"q": "10. I ___ to pass the test because I ___ hard for a whole week.", "answer": "managed / had been studying", "hint": "(MANAGE, STUDY)"},
        {"q": "11. When we finally ___ at the stadium the match ___ on for half an hour.", "answer": "arrived / had been going", "hint": "(ARRIVE, GO)"},
        {"q": "12. Before we ___ for Spain, I ___ to teach her some Spanish.", "answer": "left / had offered", "hint": "(LEAVE, OFFER)"},
        {"q": "13. We ___ for 10 minutes when we finally ___ the train station.", "answer": "had been walking / saw", "hint": "(WALK, SEE)"},
        {"q": "14. The suspect ___ the house when the police ___.", "answer": "had just left / arrived", "hint": "(JUST LEAVE, ARRIVE)"},
        {"q": "15. Sampson ___ his report by the time father ___ home.", "answer": "had finished / came", "hint": "(FINISH, COME)"},
        {"q": "16. She wasn't hungry because she ___ lunch.", "answer": "had just had", "hint": "(JUST HAVE)"},
        {"q": "17. We ___ for a while before we ___ some fish.", "answer": "had been fishing / caught", "hint": "(FISH, CATCH)"},
        {"q": "18. I told the police that I ___ the man in the photo before.", "answer": "hadn't seen", "hint": "(NOT SEE)"},
    ],
},
"cmp_1": {
    "title": "Comparison — Exam 1",
    "instruction": "Fill in the blank with the correct comparative or superlative form of the adjective.",
    "questions": [
        {"q": "1. The Nile is one of ___ rivers in the world.", "answer": "the longest", "hint": "(LONG)"},
        {"q": "2. This is ___ book I have ever read.", "answer": "the most interesting", "hint": "(INTERESTING)"},
        {"q": "3. A spider is sometimes ___ than a large snake.", "answer": "more frightening", "hint": "(FRIGHTENING)"},
        {"q": "4. Mr Harper is ___ teacher in the whole school.", "answer": "the most boring", "hint": "(BORING)"},
        {"q": "5. A bike path is usually ___ than the lane of a road.", "answer": "narrower", "hint": "(NARROW)"},
        {"q": "6. People say women are ___ than men.", "answer": "more polite / politer", "hint": "(POLITE)"},
        {"q": "7. A computer is much ___ than a pocket calculator.", "answer": "more expensive", "hint": "(EXPENSIVE)"},
        {"q": "8. My sister is not as ___ as her mother.", "answer": "tall", "hint": "(TALL)"},
        {"q": "9. Snowboarding is ___ than skiing.", "answer": "more exciting", "hint": "(EXCITING)"},
        {"q": "10. Children usually have ___ money to spend than teenagers.", "answer": "less", "hint": "(LITTLE)"},
        {"q": "11. July and August are normally ___ months of the year.", "answer": "the hottest", "hint": "(HOT)"},
        {"q": "12. Paul is ___ runner in our class.", "answer": "the slowest", "hint": "(SLOW)"},
        {"q": "13. In this test she has made ___ mistakes than in the last one.", "answer": "fewer", "hint": "(FEW)"},
        {"q": "14. Sandra is ___ girl I know.", "answer": "the cleverest / the most clever", "hint": "(CLEVER)"},
        {"q": "15. The film I watched yesterday was ___ than the one on Saturday.", "answer": "more interesting", "hint": "(INTERESTING)"},
        {"q": "16. Peter is ___ player on our team.", "answer": "the worst", "hint": "(BAD)"},
        {"q": "17. English is not as ___ as German.", "answer": "difficult", "hint": "(DIFFICULT)"},
        {"q": "18. Bill works ___ than ever.", "answer": "harder", "hint": "(HARD)"},
        {"q": "19. Mrs Simmons is ___ teacher I have ever met.", "answer": "the most polite / the politest", "hint": "(POLITE)"},
        {"q": "20. This chair is not as ___ as the one in the living room.", "answer": "comfortable", "hint": "(COMFORTABLE)"},
    ],
},
"cmp_2": {
    "title": "Comparison — Exam 2 (Adjectives & Adverbs)",
    "instruction": "Fill in the blank with the correct comparative, superlative, or adverb form.",
    "questions": [
        {"q": "1. An elephant is ___ a kangaroo.", "answer": "stronger than", "hint": "(STRONG)"},
        {"q": "2. Our teacher is ___ that film star.", "answer": "more beautiful than", "hint": "(BEAUTIFUL)"},
        {"q": "3. A school is ___ a hospital.", "answer": "noisier than", "hint": "(NOISY)"},
        {"q": "4. Jane's hair is ___ yours.", "answer": "longer than", "hint": "(LONG)"},
        {"q": "5. John's work is ___ Mary's.", "answer": "better than", "hint": "(GOOD)"},
        {"q": "6. Yesterday was ___ today.", "answer": "hotter than", "hint": "(HOT)"},
        {"q": "7. This book is ___ that one.", "answer": "more interesting than", "hint": "(INTERESTING)"},
        {"q": "8. Athletes are usually ___ scientists.", "answer": "more famous than", "hint": "(FAMOUS)"},
        {"q": "9. I think Einstein was the ___ scientist in the world.", "answer": "most brilliant", "hint": "(BRILLIANT)"},
        {"q": "10. I am a ___ swimmer than my brother.", "answer": "better", "hint": "(GOOD)"},
        {"q": "11. Mum is the ___ person in the family.", "answer": "busiest", "hint": "(BUSY)"},
        {"q": "12. What is the ___ car in the world?", "answer": "most expensive", "hint": "(EXPENSIVE)"},
        {"q": "13. London is ___ than Athens.", "answer": "rainier", "hint": "(RAINY)"},
        {"q": "14. The book was ___ than the film.", "answer": "more frightening", "hint": "(FRIGHTENING)"},
        {"q": "15. The dog is eating ___.", "answer": "hungrily", "hint": "(HUNGRY - adverb)"},
        {"q": "16. Is she drinking the hot coffee ___?", "answer": "slowly", "hint": "(SLOW - adverb)"},
        {"q": "17. Tom plays tennis ___.", "answer": "well", "hint": "(GOOD - adverb)"},
        {"q": "18. The old lady spoke ___.", "answer": "softly", "hint": "(SOFT - adverb)"},
        {"q": "19. Write the adverb of 'nice'.", "answer": "nicely", "hint": "(NICE - adverb)"},
        {"q": "20. Write the adverb of 'happy'.", "answer": "happily", "hint": "(HAPPY - adverb)"},
    ],
},

}  # end EXAMS

CATEGORIES = {
    "psc": {"label": "📝 Present Simple vs Continuous", "exams": ["psc_1","psc_2","psc_3","psc_4","psc_5","psc_6"]},
    "ppc": {"label": "🔵 Present Perfect Simple vs Continuous", "exams": ["ppc_1","ppc_2","ppc_3","ppc_4","ppc_5","ppc_6","ppc_7"]},
    "pro": {"label": "🔤 Pronouns", "exams": ["pro_1","pro_2","pro_3"]},
    "psp": {"label": "🕐 Past Simple vs Past Perfect", "exams": ["psp_1","psp_2","psp_3","psp_4"]},
    "cmp": {"label": "📊 Comparison", "exams": ["cmp_1","cmp_2"]},
}
