# -*- coding: utf-8 -*-
"""
بانک آزمون‌های کلاسی (Class Quiz).
هر آزمون: عنوان + مدت + لیست سوال‌ها. نمره‌ی نهایی همیشه از ۱۰۰ حساب می‌شه.
هر سوال: (qtype, question, answer, options, needs_ai, context)
- qtype: "fill" (جای خالی) یا "mc" (چندگزینه‌ای)
- options: برای mc لیست گزینه‌ها؛ برای fill خالی []
- answer: جواب درست. چند جواب جایگزین با / جدا می‌شه.
- needs_ai: اگه تصحیحش ظرافت داره و باید AI کمک کنه True
- context: متنی که بالای سوال نشون داده می‌شه (مثلاً بخش اولِ یک سوال دوبخشی).
"""

QUIZZES = {}

def _q(qtype, question, answer, options=None, needs_ai=False, context=""):
    return {"qtype": qtype, "question": question, "options": options or [],
            "answer": answer, "needs_ai": needs_ai, "context": context}

# ══════════════════════════════════════════════════════════════
# Exam 1 (present simple-continuous)
# ══════════════════════════════════════════════════════════════
QUIZZES["exam1"] = {
    "title": "Exam 1 (present simple-continuous)",
    "duration_min": 30,
    "questions": [
        _q("fill", "You can't see Jimmy now. He ____ a bath. (HAVE)",
           "is having/'s having"),
        _q("fill", "He ____ to the theatre. (NEVER GO)",
           "never goes"),
        _q("fill", "Anne ____ all her clothes herself. (MAKE)",
           "makes"),
        _q("fill", "At the moment she ____ a dress for a fancy dress party. (MAKE)",
           "is making/'s making",
           context="Anne makes all her clothes herself."),
        _q("fill", "He usually ____ coffee for breakfast. (HAVE)",
           "has"),
        _q("fill", "But today he ____ tea. (HAVE)",
           "is having/'s having",
           context="He usually has coffee for breakfast."),
        _q("fill", "I can't go home now because it ____ . (RAIN)",
           "is raining/'s raining"),
        _q("fill", "And I ____ an umbrella. (NOT HAVE)",
           "do not have/don't have/have not got/haven't got",
           context="I can't go home now because it's raining."),
        _q("fill", "In Britain women normally ____ hats. (NOT WEAR)",
           "do not wear/don't wear"),
        _q("fill", "The sun ____ in the east. (RISE)",
           "rises"),
        _q("fill", "And ____ in the west. (SET)",
           "sets",
           context="The sun rises in the east."),
        _q("fill", "Who ____ that terrible noise outside? (MAKE)",
           "is making/'s making"),
        _q("fill", "It's Dad. He ____ the lawn. (MOW)",
           "is mowing/'s mowing",
           context="Who is making that terrible noise outside?"),
        _q("fill", "I ____ this weekend near the coast. (SPEND)",
           "am spending/'m spending"),
        _q("fill", "I ____ there nearly every weekend. (GO)",
           "go",
           context="I'm spending this weekend near the coast."),
        _q("fill", "She ____ thirty cigarettes a day. (SMOKE)",
           "smokes"),
        _q("fill", "But at the moment she ____ to stop. (TRY)",
           "is trying/'s trying",
           context="She smokes thirty cigarettes a day."),
        _q("fill", "We ____ breakfast together every Sunday morning. (HAVE)",
           "have"),
        _q("fill", "What's that smell? It's in the kitchen. Something ____ . (BURN)",
           "is burning/'s burning"),
        _q("fill", "Who ____ to on the phone? – It's my friend Carry. (YOU SPEAK)",
           "are you speaking"),
        _q("fill", "I ____ overtime this month. (WORK)",
           "am working/'m working"),
        _q("fill", "Because I ____ up some money to buy a new car. (SAVE)",
           "am saving/'m saving",
           context="I am working overtime this month."),
        _q("fill", "The moon ____ around the earth. (GO)",
           "goes"),
        _q("fill", "She usually ____ languages very quickly. (LEARN)",
           "learns"),
        _q("fill", "But she ____ problems with Chinese. (HAVE)",
           "is having/'s having/has", needs_ai=True,
           context="She usually learns languages very quickly."),
        _q("fill", "____ TV every evening? (YOU WATCH)",
           "do you watch"),
        _q("fill", "He always ____ his bills on time. (PAY)",
           "pays"),
        _q("fill", "How long ____ you to get to the office? (IT TAKE)",
           "does it take"),
        _q("fill", "It ____ me about half an hour. (TAKE)",
           "takes",
           context="How long does it take you to get to the office?"),
        _q("fill", "The plane that ____ Heathrow at 9.15 is on schedule. (LEAVE)",
           "leaves"),
    ],
}

# ══════════════════════════════════════════════════════════════
# Exam 0 (Tenses structures) — ۱۲ زمان انگلیسی Active
# جمله‌های پایه: Sarah/study English ، They/build a house ، I/work on the project
# ══════════════════════════════════════════════════════════════
QUIZZES["exam0"] = {
    "title": "Exam 0 (Tenses structures)",
    "duration_min": 20,
    "questions": [
        _q("fill", "Sarah ____ English every single day. (Present Simple)",
           "studies",
           context="Base sentence: Sarah / study English"),
        _q("fill", "Sarah ____ English right now; she is resting. (Present Continuous - negative)",
           "is not studying/isn't studying",
           context="Base sentence: Sarah / study English"),
        _q("fill", "____ English before? (Present Perfect - question)",
           "Has Sarah studied/has studied", needs_ai=True,
           context="Base sentence: Sarah / study English   (e.g. Has Sarah studied ...?)"),
        _q("fill", "Sarah is tired because she ____ English for three hours. (Present Perfect Continuous)",
           "has been studying",
           context="Base sentence: Sarah / study English"),
        _q("fill", "They ____ a house last year; they didn't have enough money. (Past Simple - negative)",
           "did not build/didn't build",
           context="Base sentence: They / build a house"),
        _q("fill", "At this exact time yesterday they ____ a house. (Past Continuous)",
           "were building",
           context="Base sentence: They / build a house"),
        _q("fill", "____ the house before winter arrived? (Past Perfect - question)",
           "Had they built/had built", needs_ai=True,
           context="Base sentence: They / build a house   (e.g. Had they built ...?)"),
        _q("fill", "They ____ the house for months before the storm hit. (Past Perfect Continuous)",
           "had been building",
           context="Base sentence: They / build a house"),
        _q("fill", "I ____ on the project tomorrow because it's a holiday. (Future Simple - negative)",
           "will not work/won't work",
           context="Base sentence: I / work on the project"),
        _q("fill", "This time tomorrow evening I ____ on the project. (Future Continuous)",
           "will be working",
           context="Base sentence: I / work on the project"),
        _q("fill", "____ on the project by next Friday? (Future Perfect - question)",
           "Will I have worked/will have worked", needs_ai=True,
           context="Base sentence: I / work on the project   (e.g. Will I have worked ...?)"),
        _q("fill", "By next month I ____ on the project for half a year. (Future Perfect Continuous)",
           "will have been working",
           context="Base sentence: I / work on the project"),
    ],
}

QUIZZES["exam2"] = {
    "title": "Exam 2 (past simple/present simple/present continuous)",
    "duration_min": 30,
    "questions": [
        _q("fill", "Look! Steve ____ with another girl. (DANCE)", "is dancing/'s dancing"),
        _q("fill", "Joe said something funny and we all ____ . (LAUGH)", "laughed"),
        _q("fill", "Nick ____ from early morning until late at night every day. (WORK)", "works/worked"),
        _q("fill", "I was surprised that Allan ____ . (NOT WIN)", "did not win/didn't win"),
        _q("fill", "Alex was looking for the treasure, but he ____ it. (NOT FIND)", "did not find/didn't find"),
        _q("fill", "Richard ____ Kate something to drink, but she wasn't thirsty. (OFFER)", "offered"),
        _q("fill", "Tom is much shorter and ____ much less than Jack. (WEIGH)", "weighs"),
        _q("fill", "We ____ at home because it's raining. (STAY)", "are staying/'re staying"),
        _q("fill", "James ____ a love letter to Cindy. (WRITE)", "wrote"),
        _q("fill", "But he never ____ it to her. (GIVE)", "gave", context="James wrote a love letter to Cindy."),
        _q("fill", "When was the last time you ____ Christmas with your whole family? (CELEBRATE)", "celebrated"),
        _q("fill", "Bill typically ____ his work at 2:30. (FINISH)", "finishes"),
        _q("fill", "Roy ____ to come into the office on Mondays. (NOT NEED)", "does not need/doesn't need"),
        _q("fill", "In Japan, the new school year ____ in April. (BEGIN)", "begins"),
        _q("fill", "Could you please be quieter? David ____ . (SLEEP)", "is sleeping/'s sleeping"),
        _q("fill", "Neil can get there in ten minutes if he ____ fast. (DRIVE)", "drives"),
        _q("fill", "Why ____ to name your son Simon? (you DECIDE)", "did you decide", needs_ai=True),
        _q("fill", "Sam ____ his car at least once a week. (WASH)", "washes"),
        _q("fill", "____ the news on TV every day? (you WATCH)", "do you watch", needs_ai=True),
        _q("fill", "How often ____ at yourself in the mirror? (you LOOK)", "do you look", needs_ai=True),
        _q("fill", "Edward ____ that picture last summer. (PAINT)", "painted"),
        _q("fill", "The girl ____ to her feet. (JUMP)", "jumped"),
        _q("fill", "And she ____ the room. (LEAVE)", "left", context="The girl jumped to her feet."),
        _q("fill", "She feeds her dog the same thing that she ____ . (EAT)", "eats"),
        _q("fill", "Lisa ____ Randy every time she's in the United States. (VISIT)", "visits"),
        _q("fill", "Do you want to hear about what I ____ last summer? (DO)", "did"),
        _q("fill", "Alex ____ into bed. (GET)", "got"),
        _q("fill", "And he ____ the light. (TURN OFF)", "turned off", context="Alex got into bed."),
        _q("fill", "____ green or black tea? (you PREFER)", "do you prefer", needs_ai=True),
        _q("fill", "____ anybody who can teach my kids French? (you KNOW)", "do you know", needs_ai=True),
        _q("fill", "Look at the boy and the dog that ____ over there. (RUN)", "are running/'re running"),
        _q("fill", "Tom said that he hated the song we ____ last night. (SING)", "sang"),
        _q("fill", "The weather was cold and it ____ a lot. (RAIN)", "rained"),
    ],
}

QUIZZES["exam3"] = {
    "title": "Exam 3 (pronoun - rather)",
    "duration_min": 30,
    "questions": [
        # ── Subjective pronouns ──
        _q("fill", "My sister is a nurse. ____ works at the hospital. (subjective pronoun)", "she"),
        _q("mc", "Tom and I are friends. ____ play football together.", "we",
           options=["we","us","our","they"]),
        _q("fill", "Look at the birds. ____ are flying south. (subjective pronoun)", "they"),
        _q("mc", "Where is the book? ____ is on the table.", "it",
           options=["it","its","it's","he"]),
        # ── Objective pronouns ──
        _q("fill", "I like Sara. I always help ____ with homework. (objective pronoun)", "her"),
        _q("mc", "These flowers are beautiful. Can you give ____ to me?", "them",
           options=["them","they","their","theirs"]),
        _q("fill", "This gift is for you. I bought it for ____ . (objective pronoun)", "you"),
        _q("mc", "He is my best friend. I trust ____ completely.", "him",
           options=["him","he","his","himself"]),
        # ── Possessive (adjective + pronoun) ──
        _q("fill", "This is not your pen. It is ____ pen. (possessive: belongs to me)", "my"),
        _q("mc", "That car is ____ . We bought it last year.", "ours",
           options=["ours","our","us","ourselves"]),
        _q("fill", "This book is ____ . Sara gave it to me, so it belongs to me now. (possessive pronoun)", "mine"),
        _q("mc", "Is this ____ jacket? It was on your chair.", "your",
           options=["your","yours","you","yourself"]),
        _q("fill", "The dog wagged ____ tail happily. (possessive adjective for 'the dog')", "its"),
        # ── Reflexive pronouns ──
        _q("fill", "She cut ____ while cooking dinner. (reflexive pronoun)", "herself"),
        _q("mc", "Be careful! Don't hurt ____ .", "yourself",
           options=["yourself","yourselves","you","your"]),
        _q("fill", "The children drew the pictures ____ . (reflexive: they did it alone)", "themselves"),
        _q("mc", "I made this cake ____ .", "myself",
           options=["myself","meself","me","mine"]),
        # ── Indefinite pronouns ──
        _q("fill", "Is there ____ at home? I knocked but no one answered. (indefinite pronoun: any person)", "anyone/anybody"),
        _q("mc", "____ is here. The room is completely empty.", "Nobody",
           options=["Nobody","Anybody","Everybody","Somebody"]),
        _q("fill", "I'm hungry. I want ____ to eat. (indefinite pronoun: a thing, positive sentence)", "something"),
        _q("mc", "____ wants to be happy in life.", "Everyone",
           options=["Everyone","Anyone","No one","It"]),
        _q("fill", "She looked everywhere but couldn't find ____ . (indefinite pronoun: not a thing, negative)", "anything"),
        # ── would rather ──
        _q("fill", "I would ____ stay home than go out tonight. (would ___ = prefer to)", "rather"),
        _q("mc", "I'd rather ____ tea than coffee.", "have",
           options=["have","to have","having","had"]),
        _q("fill", "Complete: She would rather walk ____ take the bus. (which word?)", "than"),
        _q("mc", "We'd rather ____ at home this weekend.", "stay",
           options=["stay","to stay","staying","stayed"]),
        # ── prefer ──
        _q("fill", "I prefer tea ____ coffee. (preposition after 'prefer' + noun)", "to"),
        _q("mc", "She prefers ____ early in the morning.", "to exercise",
           options=["to exercise","exercise","exercises","exercised"]),
        _q("fill", "I prefer reading ____ watching TV. (prefer + -ing ___ -ing)", "to"),
        _q("mc", "They prefer coffee ____ tea.", "to",
           options=["to","than","from","over"]),
    ],
}

QUIZZES["exam4"] = {
    "title": "Exam 4 (relative clause)",
    "duration_min": 30,
    "seconds_per_q": 90,
    "questions": [
        _q("fill", "Combine into ONE sentence using a relative pronoun:\nWe talked about the party. Sarah wants to organize it for my birthday.",
           "We talked about the party that Sarah wants to organize for my birthday/We talked about the party which Sarah wants to organize for my birthday/We talked about the party Sarah wants to organize for my birthday",
           needs_ai=True),
        _q("fill", "Combine into ONE sentence using a relative pronoun:\nMrs Flowers has paintings in her house. They are worth over $10,000.",
           "Mrs Flowers has paintings in her house that are worth over $10,000/Mrs Flowers has paintings in her house which are worth over $10,000",
           needs_ai=True),
        _q("fill", "Combine into ONE sentence using a relative pronoun:\nThe couple lives next to us. Their daughter has two charming boys.",
           "The couple, whose daughter has two charming boys, lives next to us",
           needs_ai=True),
        _q("fill", "Combine into ONE sentence using a relative pronoun:\nThis is the house. I had my first party here.",
           "This is the house where I had my first party/This is the house that I had my first party in/This is the house I had my first party in",
           needs_ai=True),
        _q("fill", "Combine into ONE sentence using a relative pronoun:\nJerry received a bad mark on his essay. It was only one page long.",
           "Jerry received a bad mark on his essay, which was only one page long",
           needs_ai=True),
        _q("fill", "Combine into ONE sentence using a relative pronoun:\nIngrid went to see the doctor yesterday. He is a friend of hers.",
           "Ingrid went to see the doctor, who is a friend of hers, yesterday",
           needs_ai=True),
        _q("fill", "Combine into ONE sentence using a relative pronoun:\nMr Reynolds had to do all the work himself. His secretary left a few days ago.",
           "Mr Reynolds, whose secretary left a few days ago, had to do all the work himself",
           needs_ai=True),
        _q("fill", "Combine into ONE sentence using a relative pronoun:\nThe boy took the photograph. He gave it to his mother.",
           "The boy took the photograph, which he gave to his mother",
           needs_ai=True),
        _q("fill", "Combine into ONE sentence using a relative pronoun:\nThat is the man. I met him at Alice's party.",
           "That is the man who I met at Alice's party/That is the man whom I met at Alice's party/That is the man that I met at Alice's party/That is the man I met at Alice's party",
           needs_ai=True),
        _q("fill", "Combine into ONE sentence using a relative pronoun:\nThe boy smiled. Elena gave him some money.",
           "The boy who Elena gave some money to smiled/The boy whom Elena gave some money to smiled/The boy that Elena gave some money to smiled/The boy Elena gave some money to smiled",
           needs_ai=True),
        _q("fill", "Combine into ONE sentence using a relative pronoun:\nSteven is an architect. His designs have won many awards.",
           "Steven, whose designs have won many awards, is an architect",
           needs_ai=True),
        _q("fill", "Combine into ONE sentence using a relative pronoun:\nDecorating is a difficult job. I hate it.",
           "Decorating is a difficult job that I hate/Decorating is a difficult job which I hate/Decorating is a difficult job I hate/I hate decorating, which is a difficult job",
           needs_ai=True),
        _q("fill", "Combine into ONE sentence using a relative pronoun:\nChristmas is a day. People are happy.",
           "Christmas is a day when people are happy/Christmas is a day that people are happy/Christmas is a day on which people are happy",
           needs_ai=True),
        _q("fill", "Combine into ONE sentence using a relative pronoun:\nWe went to the restaurant. We had met there before.",
           "We went to the restaurant where we had met before/We went to the restaurant that we had met at before/We went to the restaurant we had met at before",
           needs_ai=True),
        _q("fill", "Combine into ONE sentence using a relative pronoun:\nThe woman called yesterday. She wants to buy the house.",
           "The woman who called yesterday wants to buy the house/The woman that called yesterday wants to buy the house/The woman who wants to buy the house called yesterday",
           needs_ai=True),
    ],
}

if __name__ == "__main__":
    for k, v in QUIZZES.items():
        n = len(v['questions'])
        per = round(100 / n, 2)
        ai = sum(1 for q in v['questions'] if q['needs_ai'])
        ctx = sum(1 for q in v['questions'] if q['context'])
        print(f"{k}: {v['title']}")
        print(f"  {n} سوال × {per} نمره = 100 | {ai} سوال نیاز به AI | {ctx} سوال context دارن")
