# -*- coding: utf-8 -*-
"""
بانک آزمون‌های کلاسی (Class Quiz).
هر آزمون: عنوان + مدت + لیست سوال‌ها. نمره‌ی نهایی همیشه از ۱۰۰ حساب می‌شه.
هر سوال: (qtype, question, answer, options, needs_ai, context)
- qtype: "fill" (جای خالی) یا "mc" (چندگزینه‌ای)
- options: برای mc لیست گزینه‌ها؛ برای fill خالی []
- answer: جواب درست. چند جواب جایگزین با / جدا می‌شه.
- needs_ai: اگه تصحیحش ظرافت داره و باید AI کمک کنه True
- context: متنی که بالای سوال نشون داده می‌شه (مثلاً بخش اولِ یک سوال دوبخشی).
"""

QUIZZES = {}

def _q(qtype, question, answer, options=None, needs_ai=False, context=""):
    return {"qtype": qtype, "question": question, "options": options or [],
            "answer": answer, "needs_ai": needs_ai, "context": context}

# ══════════════════════════════════════════════════════════════
# Exam 1 (present simple-continuous)
# ══════════════════════════════════════════════════════════════
QUIZZES["exam1"] = {
    "title": "Exam 1 (present simple-continuous)",
    "duration_min": 30,
    "questions": [
        _q("fill", "You can't see Jimmy now. He ____ a bath. (HAVE)",
           "is having/'s having"),
        _q("fill", "He ____ to the theatre. (NEVER GO)",
           "never goes"),
        _q("fill", "Anne ____ all her clothes herself. (MAKE)",
           "makes"),
        _q("fill", "At the moment she ____ a dress for a fancy dress party. (MAKE)",
           "is making/'s making",
           context="Anne makes all her clothes herself."),
        _q("fill", "He usually ____ coffee for breakfast. (HAVE)",
           "has"),
        _q("fill", "But today he ____ tea. (HAVE)",
           "is having/'s having",
           context="He usually has coffee for breakfast."),
        _q("fill", "I can't go home now because it ____ . (RAIN)",
           "is raining/'s raining"),
        _q("fill", "And I ____ an umbrella. (NOT HAVE)",
           "do not have/don't have/have not got/haven't got",
           context="I can't go home now because it's raining."),
        _q("fill", "In Britain women normally ____ hats. (NOT WEAR)",
           "do not wear/don't wear"),
        _q("fill", "The sun ____ in the east. (RISE)",
           "rises"),
        _q("fill", "And ____ in the west. (SET)",
           "sets",
           context="The sun rises in the east."),
        _q("fill", "Who ____ that terrible noise outside? (MAKE)",
           "is making/'s making"),
        _q("fill", "It's Dad. He ____ the lawn. (MOW)",
           "is mowing/'s mowing",
           context="Who is making that terrible noise outside?"),
        _q("fill", "I ____ this weekend near the coast. (SPEND)",
           "am spending/'m spending"),
        _q("fill", "I ____ there nearly every weekend. (GO)",
           "go",
           context="I'm spending this weekend near the coast."),
        _q("fill", "She ____ thirty cigarettes a day. (SMOKE)",
           "smokes"),
        _q("fill", "But at the moment she ____ to stop. (TRY)",
           "is trying/'s trying",
           context="She smokes thirty cigarettes a day."),
        _q("fill", "We ____ breakfast together every Sunday morning. (HAVE)",
           "have"),
        _q("fill", "What's that smell? It's in the kitchen. Something ____ . (BURN)",
           "is burning/'s burning"),
        _q("fill", "Who ____ to on the phone? – It's my friend Carry. (YOU SPEAK)",
           "are you speaking"),
        _q("fill", "I ____ overtime this month. (WORK)",
           "am working/'m working"),
        _q("fill", "Because I ____ up some money to buy a new car. (SAVE)",
           "am saving/'m saving",
           context="I am working overtime this month."),
        _q("fill", "The moon ____ around the earth. (GO)",
           "goes"),
        _q("fill", "She usually ____ languages very quickly. (LEARN)",
           "learns"),
        _q("fill", "But she ____ problems with Chinese. (HAVE)",
           "is having/'s having/has", needs_ai=True,
           context="She usually learns languages very quickly."),
        _q("fill", "____ TV every evening? (YOU WATCH)",
           "do you watch"),
        _q("fill", "He always ____ his bills on time. (PAY)",
           "pays"),
        _q("fill", "How long ____ you to get to the office? (IT TAKE)",
           "does it take"),
        _q("fill", "It ____ me about half an hour. (TAKE)",
           "takes",
           context="How long does it take you to get to the office?"),
        _q("fill", "The plane that ____ Heathrow at 9.15 is on schedule. (LEAVE)",
           "leaves"),
    ],
}

# ══════════════════════════════════════════════════════════════
# Exam 0 (Tenses structures) — ۱۲ زمان انگلیسی Active
# جمله‌های پایه: Sarah/study English ، They/build a house ، I/work on the project
# ══════════════════════════════════════════════════════════════
QUIZZES["exam0"] = {
    "title": "Exam 0 (Tenses structures)",
    "duration_min": 20,
    "questions": [
        _q("fill", "Sarah ____ English every single day. (Present Simple)",
           "studies",
           context="Base sentence: Sarah / study English"),
        _q("fill", "Sarah ____ English right now; she is resting. (Present Continuous - negative)",
           "is not studying/isn't studying",
           context="Base sentence: Sarah / study English"),
        _q("fill", "____ English before? (Present Perfect - question)",
           "Has Sarah studied/has studied", needs_ai=True,
           context="Base sentence: Sarah / study English   (e.g. Has Sarah studied ...?)"),
        _q("fill", "Sarah is tired because she ____ English for three hours. (Present Perfect Continuous)",
           "has been studying",
           context="Base sentence: Sarah / study English"),
        _q("fill", "They ____ a house last year; they didn't have enough money. (Past Simple - negative)",
           "did not build/didn't build",
           context="Base sentence: They / build a house"),
        _q("fill", "At this exact time yesterday they ____ a house. (Past Continuous)",
           "were building",
           context="Base sentence: They / build a house"),
        _q("fill", "____ the house before winter arrived? (Past Perfect - question)",
           "Had they built/had built", needs_ai=True,
           context="Base sentence: They / build a house   (e.g. Had they built ...?)"),
        _q("fill", "They ____ the house for months before the storm hit. (Past Perfect Continuous)",
           "had been building",
           context="Base sentence: They / build a house"),
        _q("fill", "I ____ on the project tomorrow because it's a holiday. (Future Simple - negative)",
           "will not work/won't work",
           context="Base sentence: I / work on the project"),
        _q("fill", "This time tomorrow evening I ____ on the project. (Future Continuous)",
           "will be working",
           context="Base sentence: I / work on the project"),
        _q("fill", "____ on the project by next Friday? (Future Perfect - question)",
           "Will I have worked/will have worked", needs_ai=True,
           context="Base sentence: I / work on the project   (e.g. Will I have worked ...?)"),
        _q("fill", "By next month I ____ on the project for half a year. (Future Perfect Continuous)",
           "will have been working",
           context="Base sentence: I / work on the project"),
    ],
}

QUIZZES["exam2"] = {
    "title": "Exam 2 (past simple/present simple/present continuous)",
    "duration_min": 30,
    "questions": [
        _q("fill", "Look! Steve ____ with another girl. (DANCE)", "is dancing/'s dancing"),
        _q("fill", "Joe said something funny and we all ____ . (LAUGH)", "laughed"),
        _q("fill", "Nick ____ from early morning until late at night every day. (WORK)", "works/worked"),
        _q("fill", "I was surprised that Allan ____ . (NOT WIN)", "did not win/didn't win"),
        _q("fill", "Alex was looking for the treasure, but he ____ it. (NOT FIND)", "did not find/didn't find"),
        _q("fill", "Richard ____ Kate something to drink, but she wasn't thirsty. (OFFER)", "offered"),
        _q("fill", "Tom is much shorter and ____ much less than Jack. (WEIGH)", "weighs"),
        _q("fill", "We ____ at home because it's raining. (STAY)", "are staying/'re staying"),
        _q("fill", "James ____ a love letter to Cindy. (WRITE)", "wrote"),
        _q("fill", "But he never ____ it to her. (GIVE)", "gave", context="James wrote a love letter to Cindy."),
        _q("fill", "When was the last time you ____ Christmas with your whole family? (CELEBRATE)", "celebrated"),
        _q("fill", "Bill typically ____ his work at 2:30. (FINISH)", "finishes"),
        _q("fill", "Roy ____ to come into the office on Mondays. (NOT NEED)", "does not need/doesn't need"),
        _q("fill", "In Japan, the new school year ____ in April. (BEGIN)", "begins"),
        _q("fill", "Could you please be quieter? David ____ . (SLEEP)", "is sleeping/'s sleeping"),
        _q("fill", "Neil can get there in ten minutes if he ____ fast. (DRIVE)", "drives"),
        _q("fill", "Why ____ to name your son Simon? (you DECIDE)", "did you decide", needs_ai=True),
        _q("fill", "Sam ____ his car at least once a week. (WASH)", "washes"),
        _q("fill", "____ the news on TV every day? (you WATCH)", "do you watch", needs_ai=True),
        _q("fill", "How often ____ at yourself in the mirror? (you LOOK)", "do you look", needs_ai=True),
        _q("fill", "Edward ____ that picture last summer. (PAINT)", "painted"),
        _q("fill", "The girl ____ to her feet. (JUMP)", "jumped"),
        _q("fill", "And she ____ the room. (LEAVE)", "left", context="The girl jumped to her feet."),
        _q("fill", "She feeds her dog the same thing that she ____ . (EAT)", "eats"),
        _q("fill", "Lisa ____ Randy every time she's in the United States. (VISIT)", "visits"),
        _q("fill", "Do you want to hear about what I ____ last summer? (DO)", "did"),
        _q("fill", "Alex ____ into bed. (GET)", "got"),
        _q("fill", "And he ____ the light. (TURN OFF)", "turned off", context="Alex got into bed."),
        _q("fill", "____ green or black tea? (you PREFER)", "do you prefer", needs_ai=True),
        _q("fill", "____ anybody who can teach my kids French? (you KNOW)", "do you know", needs_ai=True),
        _q("fill", "Look at the boy and the dog that ____ over there. (RUN)", "are running/'re running"),
        _q("fill", "Tom said that he hated the song we ____ last night. (SING)", "sang"),
        _q("fill", "The weather was cold and it ____ a lot. (RAIN)", "rained"),
    ],
}

QUIZZES["exam3"] = {
    "title": "Exam 3 (pronoun - rather)",
    "duration_min": 30,
    "questions": [
        # ── Subjective pronouns ──
        _q("fill", "My sister is a nurse. ____ works at the hospital. (subjective pronoun)", "she"),
        _q("mc", "Tom and I are friends. ____ play football together.", "we",
           options=["we","us","our","they"]),
        _q("fill", "Look at the birds. ____ are flying south. (subjective pronoun)", "they"),
        _q("mc", "Where is the book? ____ is on the table.", "it",
           options=["it","its","it's","he"]),
        # ── Objective pronouns ──
        _q("fill", "I like Sara. I always help ____ with homework. (objective pronoun)", "her"),
        _q("mc", "These flowers are beautiful. Can you give ____ to me?", "them",
           options=["them","they","their","theirs"]),
        _q("fill", "This gift is for you. I bought it for ____ . (objective pronoun)", "you"),
        _q("mc", "He is my best friend. I trust ____ completely.", "him",
           options=["him","he","his","himself"]),
        # ── Possessive (adjective + pronoun) ──
        _q("fill", "This is not your pen. It is ____ pen. (possessive: belongs to me)", "my"),
        _q("mc", "That car is ____ . We bought it last year.", "ours",
           options=["ours","our","us","ourselves"]),
        _q("fill", "This book is ____ . Sara gave it to me, so it belongs to me now. (possessive pronoun)", "mine"),
        _q("mc", "Is this ____ jacket? It was on your chair.", "your",
           options=["your","yours","you","yourself"]),
        _q("fill", "The dog wagged ____ tail happily. (possessive adjective for 'the dog')", "its"),
        # ── Reflexive pronouns ──
        _q("fill", "She cut ____ while cooking dinner. (reflexive pronoun)", "herself"),
        _q("mc", "Be careful! Don't hurt ____ .", "yourself",
           options=["yourself","yourselves","you","your"]),
        _q("fill", "The children drew the pictures ____ . (reflexive: they did it alone)", "themselves"),
        _q("mc", "I made this cake ____ .", "myself",
           options=["myself","meself","me","mine"]),
        # ── Indefinite pronouns ──
        _q("fill", "Is there ____ at home? I knocked but no one answered. (indefinite pronoun: any person)", "anyone/anybody"),
        _q("mc", "____ is here. The room is completely empty.", "Nobody",
           options=["Nobody","Anybody","Everybody","Somebody"]),
        _q("fill", "I'm hungry. I want ____ to eat. (indefinite pronoun: a thing, positive sentence)", "something"),
        _q("mc", "____ wants to be happy in life.", "Everyone",
           options=["Everyone","Anyone","No one","It"]),
        _q("fill", "She looked everywhere but couldn't find ____ . (indefinite pronoun: not a thing, negative)", "anything"),
        # ── would rather ──
        _q("fill", "I would ____ stay home than go out tonight. (would ___ = prefer to)", "rather"),
        _q("mc", "I'd rather ____ tea than coffee.", "have",
           options=["have","to have","having","had"]),
        _q("fill", "Complete: She would rather walk ____ take the bus. (which word?)", "than"),
        _q("mc", "We'd rather ____ at home this weekend.", "stay",
           options=["stay","to stay","staying","stayed"]),
        # ── prefer ──
        _q("fill", "I prefer tea ____ coffee. (preposition after 'prefer' + noun)", "to"),
        _q("mc", "She prefers ____ early in the morning.", "to exercise",
           options=["to exercise","exercise","exercises","exercised"]),
        _q("fill", "I prefer reading ____ watching TV. (prefer + -ing ___ -ing)", "to"),
        _q("mc", "They prefer coffee ____ tea.", "to",
           options=["to","than","from","over"]),
    ],
}

QUIZZES["exam4"] = {
    "title": "Exam 4 (relative clause)",
    "duration_min": 30,
    "seconds_per_q": 90,
    "questions": [
        _q("fill", "Combine into ONE sentence using a relative pronoun:\nWe talked about the party. Sarah wants to organize it for my birthday.",
           "We talked about the party that Sarah wants to organize for my birthday/We talked about the party which Sarah wants to organize for my birthday/We talked about the party Sarah wants to organize for my birthday",
           needs_ai=True),
        _q("fill", "Combine into ONE sentence using a relative pronoun:\nMrs Flowers has paintings in her house. They are worth over $10,000.",
           "Mrs Flowers has paintings in her house that are worth over $10,000/Mrs Flowers has paintings in her house which are worth over $10,000",
           needs_ai=True),
        _q("fill", "Combine into ONE sentence using a relative pronoun:\nThe couple lives next to us. Their daughter has two charming boys.",
           "The couple, whose daughter has two charming boys, lives next to us",
           needs_ai=True),
        _q("fill", "Combine into ONE sentence using a relative pronoun:\nThis is the house. I had my first party here.",
           "This is the house where I had my first party/This is the house that I had my first party in/This is the house I had my first party in",
           needs_ai=True),
        _q("fill", "Combine into ONE sentence using a relative pronoun:\nJerry received a bad mark on his essay. It was only one page long.",
           "Jerry received a bad mark on his essay, which was only one page long",
           needs_ai=True),
        _q("fill", "Combine into ONE sentence using a relative pronoun:\nIngrid went to see the doctor yesterday. He is a friend of hers.",
           "Ingrid went to see the doctor, who is a friend of hers, yesterday",
           needs_ai=True),
        _q("fill", "Combine into ONE sentence using a relative pronoun:\nMr Reynolds had to do all the work himself. His secretary left a few days ago.",
           "Mr Reynolds, whose secretary left a few days ago, had to do all the work himself",
           needs_ai=True),
        _q("fill", "Combine into ONE sentence using a relative pronoun:\nThe boy took the photograph. He gave it to his mother.",
           "The boy took the photograph, which he gave to his mother",
           needs_ai=True),
        _q("fill", "Combine into ONE sentence using a relative pronoun:\nThat is the man. I met him at Alice's party.",
           "That is the man who I met at Alice's party/That is the man whom I met at Alice's party/That is the man that I met at Alice's party/That is the man I met at Alice's party",
           needs_ai=True),
        _q("fill", "Combine into ONE sentence using a relative pronoun:\nThe boy smiled. Elena gave him some money.",
           "The boy who Elena gave some money to smiled/The boy whom Elena gave some money to smiled/The boy that Elena gave some money to smiled/The boy Elena gave some money to smiled",
           needs_ai=True),
        _q("fill", "Combine into ONE sentence using a relative pronoun:\nSteven is an architect. His designs have won many awards.",
           "Steven, whose designs have won many awards, is an architect",
           needs_ai=True),
        _q("fill", "Combine into ONE sentence using a relative pronoun:\nDecorating is a difficult job. I hate it.",
           "Decorating is a difficult job that I hate/Decorating is a difficult job which I hate/Decorating is a difficult job I hate/I hate decorating, which is a difficult job",
           needs_ai=True),
        _q("fill", "Combine into ONE sentence using a relative pronoun:\nChristmas is a day. People are happy.",
           "Christmas is a day when people are happy/Christmas is a day that people are happy/Christmas is a day on which people are happy",
           needs_ai=True),
        _q("fill", "Combine into ONE sentence using a relative pronoun:\nWe went to the restaurant. We had met there before.",
           "We went to the restaurant where we had met before/We went to the restaurant that we had met at before/We went to the restaurant we had met at before",
           needs_ai=True),
        _q("fill", "Combine into ONE sentence using a relative pronoun:\nThe woman called yesterday. She wants to buy the house.",
           "The woman who called yesterday wants to buy the house/The woman that called yesterday wants to buy the house/The woman who wants to buy the house called yesterday",
           needs_ai=True),
    ],
}

QUIZZES["exam5"] = {
    "title": "Exam 5 (present perfect-past simple)",
    "duration_min": 30,
    "questions": [
        _q("fill", "The weather around here ____ terrible in the last few weeks. (BE)", "has been/'s been"),
        _q("fill", "Maria ____ her suitcase last night. (PACK)", "packed"),
        _q("fill", "I ____ volleyball since I was a teenager. (NOT PLAY)", "have not played/haven't played"),
        _q("fill", "We ____ wash the dishes. They're all clean now. (HELP)", "have helped/'ve helped"),
        _q("fill", "They ____ the factory. (CLOSE)", "have closed/'ve closed"),
        _q("fill", "Really? When ____ ? (THAT HAPPEN)", "did that happen", needs_ai=True, context="They have closed the factory."),
        _q("fill", "____ yet? (YOUR BUSINESS COURSE - START)", "has your business course started", needs_ai=True),
        _q("fill", "How long ____ that camera? (YOU HAVE)", "have you had", needs_ai=True),
        _q("fill", "About a month. I ____ it because it was on sale just before Christmas. (BUY)", "bought", context="How long have you had that camera? About a month."),
        _q("fill", "____ last week's magazine? (YOU SEE)", "have you seen", needs_ai=True),
        _q("fill", "It must be here because I ____ it on Monday. (BUY)", "bought", context="Have you seen last week's magazine?"),
        _q("fill", "The books you ordered ____ . (ARRIVE)", "have arrived/'ve arrived"),
        _q("fill", "The delivery service ____ them an hour ago. (BRING)", "brought", context="The books you ordered have arrived."),
        _q("fill", "The Queen ____ her two-week tour through Australia yesterday. (START)", "started"),
        _q("fill", "The plane from New York ____ . The passengers are getting out. (JUST LAND)", "has just landed/'s just landed"),
        _q("fill", "We ____ a party at school for ages. (NOT HAVE)", "have not had/haven't had"),
        _q("fill", "I ____ a cold in school a few days ago. (CATCH)", "caught"),
        _q("fill", "And I ____ ill ever since. (BE)", "have been/'ve been", context="I caught a cold in school a few days ago."),
        _q("fill", "Dinosaurs ____ around the earth millions of years ago. (WANDER)", "wandered"),
        _q("fill", "Prices ____ up last year. (NOT GO)", "did not go/didn't go"),
        _q("fill", "But they ____ by 8% already this year. (INCREASE)", "have increased/'ve increased", context="Prices didn't go up last year."),
        _q("fill", "I'm so tired. I ____ all the way to the underground station. (WALK)", "have walked/'ve walked"),
        _q("fill", "We ____ home from our holidays and getting ready to settle in. (JUST COME)", "have just come/'ve just come"),
        _q("fill", "She ____ in London for three years. (LIVE)", "lived"),
        _q("fill", "However, when her mom ____ , (DIE)", "died", context="She lived in London for three years."),
        _q("fill", "she ____ to Leeds. (MOVE)", "moved", context="She lived in London for three years; when her mom died,"),
        _q("fill", "And she ____ there ever since. (LIVE)", "has lived/'s lived", context="...she moved to Leeds."),
        _q("fill", "Dusty ____ a match so far this year. (NEVER LOSE)", "has never lost/'s never lost"),
        _q("fill", "He is more successful than last year, when he ____ the first three matches. (LOSE)", "lost", context="Dusty has never lost a match so far this year."),
        _q("fill", "He ____ off the ladder. (FALL)", "fell"),
        _q("fill", "And he ____ his ankle. (BREAK)", "broke", context="He fell off the ladder."),
        _q("fill", "That's why he ____ in school for a while. (NOT BE)", "has not been/hasn't been", context="He fell off the ladder and broke his ankle."),
    ],
}

QUIZZES["exam6"] = {
    "title": "Exam 6 (present perfect simple-continuous)",
    "duration_min": 25,
    "questions": [
        _q("fill", "I ____ several books about sailing and I am quite fascinated by the sport. (READ)", "have been reading/'ve been reading/have read/'ve read"),
        _q("fill", "You look absolutely exhausted. What ____ ? (YOU DO)", "have you been doing", needs_ai=True),
        _q("fill", "He ____ that book for over two weeks. (READ)", "has been reading/'s been reading"),
        _q("fill", "And he ____ yet. He's such a slow reader. (NOT FINISH)", "has not finished/hasn't finished", context="He has been reading that book for over two weeks."),
        _q("fill", "My sister ____ in Norwich for two months. She seems to like it there. (LIVE)", "has been living/'s been living"),
        _q("fill", "My dad ____ a new job. (JUST START)", "has just started/'s just started"),
        _q("fill", "You should put some boots on. It ____ for several days now and the ground is muddy. (RAIN)", "has been raining/'s been raining"),
        _q("fill", "____ your homework yet? (YOU FINISH)", "have you finished", needs_ai=True),
        _q("fill", "You ____ on it for hours. (WORK)", "have been working/'ve been working", context="Have you finished your homework yet?"),
        _q("fill", "Maria ____ for a job since she left school last summer. (LOOK)", "has been looking/'s been looking"),
        _q("fill", "She still ____ one. (NOT FIND)", "has not found/hasn't found", context="Maria has been looking for a job since she left school."),
        _q("fill", "They ____ TV the whole evening. (WATCH)", "have been watching/'ve been watching"),
        _q("fill", "It's their favourite film and they ____ it several times. (SEE)", "have seen/'ve seen", context="They have been watching TV the whole evening."),
        _q("fill", "I ____ him about his new girlfriend twice this week. He doesn't seem to want to answer. (ASK)", "have asked/'ve asked"),
        _q("fill", "I ____ my driving test. (JUST PASS)", "have just passed/'ve just passed"),
        _q("fill", "Where ____ ? (YOU BE)", "have you been", needs_ai=True),
        _q("fill", "At the doctor's. I ____ ill lately. (BE)", "have been/'ve been", context="Where have you been?"),
        _q("fill", "We ____ the date for the marriage. It will be on May 26. (SET)", "have set/'ve set"),
        _q("fill", "My sister ____ too many sweets lately. She must try to stop. (EAT)", "has been eating/'s been eating"),
        _q("fill", "I ____ him for ages. (NOT SEE)", "have not seen/haven't seen"),
        _q("fill", "I wonder what he ____ up to. (BE)", "has been/'s been", context="I haven't seen him for ages."),
        _q("fill", "I ____ French for three years now but I don't seem to be making any progress. (LEARN)", "have been learning/'ve been learning"),
    ],
}

QUIZZES["exam7"] = {
    "title": "Exam 7 (letter to janet)",
    "duration_min": 25,
    "questions": [
        _q("fill", "The doctor ____ yesterday. (COME)", "came"),
        _q("fill", "He ____ my cough. (NOT LIKE)", "did not like/didn't like"),
        _q("fill", "I ____ in bed since Tuesday, and I can't stand it anymore. (LIE)", "have been lying/'ve been lying"),
        _q("fill", "I ____ ill like this before. (NEVER BE)", "have never been/'ve never been"),
        _q("fill", "The weather's terrible, too. It ____ the whole week. (RAIN)", "has been raining/'s been raining"),
        _q("fill", "I can't have tea because the milkman ____ this morning. (NOT COME)", "has not come/hasn't come"),
        _q("fill", "Don't know why - I'm pretty sure I ____ his bill. (PAY)", "have paid/'ve paid"),
        _q("fill", "Alice ____ married last week. (GET)", "got"),
        _q("fill", "So now all Mary's kids ____ home. (LEAVE)", "have left/'ve left"),
        _q("fill", "Since Fred ____ of a heart attack, she has been all alone. (DIE)", "died"),
        _q("fill", "Since Fred died of a heart attack she ____ all alone. (BE)", "has been/'s been"),
        _q("fill", "We ____ neighbours for over twenty years. (BE)", "have been/'ve been"),
        _q("fill", "And she ____ friendly and helpful to me. (ALWAYS BE)", "has always been/'s always been"),
        _q("fill", "Jessica, my cleaning lady, ____ a few days ago. (LEAVE)", "left"),
        _q("fill", "I ____ her since she broke all those plates. (NOT TRUST)", "have not trusted/haven't trusted"),
        _q("fill", "I haven't trusted her since she ____ all those plates. (BREAK)", "broke"),
        _q("fill", "And ____ it was the cat. (SAY)", "said"),
        _q("fill", "She broke the plates and said it ____ the cat. (BE)", "was"),
        _q("fill", "The village ____ very much. (NOT CHANGE)", "has not changed/hasn't changed"),
        _q("fill", "A new family ____ over the grocery store recently. (TAKE)", "has taken/'s taken"),
    ],
}

QUIZZES["exam8"] = {
    "title": "Exam 8 (comparison)",
    "duration_min": 25,
    "questions": [
        _q("fill", "The Nile is one of ____ rivers in the world. (LONG)", "the longest"),
        _q("fill", "This is ____ book I have ever read. (INTERESTING)", "the most interesting"),
        _q("fill", "A spider is sometimes ____ than a large snake. (FRIGHTENING)", "more frightening"),
        _q("fill", "Mr Harper is ____ teacher in the whole school. (BORING)", "the most boring"),
        _q("fill", "He is even ____ than my French teacher. (BORING)", "more boring", context="Mr Harper is the most boring teacher in the whole school."),
        _q("fill", "A bike path is usually ____ than the lane of a road. (NARROW)", "narrower"),
        _q("fill", "People say women are ____ than men. (POLITE)", "more polite/politer"),
        _q("fill", "A computer is much ____ than a pocket calculator. (EXPENSIVE)", "more expensive"),
        _q("fill", "My sister is not as ____ as her mother. (TALL)", "tall"),
        _q("fill", "Snowboarding is ____ than skiing. (EXCITING)", "more exciting"),
        _q("fill", "Children usually have ____ money to spend than teenagers. (LITTLE)", "less"),
        _q("fill", "July and August are normally ____ months of the year. (HOT)", "the hottest"),
        _q("fill", "Paul is ____ runner in our class. (SLOW)", "the slowest"),
        _q("fill", "Nobody is ____ than he is. (SLOW)", "slower", context="Paul is the slowest runner in our class."),
        _q("fill", "In this test she has made ____ mistakes than in the last one. (FEW)", "fewer"),
        _q("fill", "Sandra is ____ girl I know. (CLEVER)", "the cleverest/the most clever"),
        _q("fill", "The film I watched yesterday was ____ than the one on Saturday. (INTERESTING)", "more interesting"),
        _q("fill", "Peter is ____ player on our team. He never gets anything right. (BAD)", "the worst"),
        _q("fill", "English is not as ____ as German. (DIFFICULT)", "difficult"),
        _q("fill", "But English is ____ than other languages. (DIFFICULT)", "more difficult", context="English is not as difficult as German."),
        _q("fill", "Bill works ____ than ever. He wants to get a promotion. (HARD)", "harder"),
        _q("fill", "Mrs Simmons is ____ teacher I have ever met. (POLITE)", "the most polite/the politest"),
        _q("fill", "This chair is not as ____ as the one in the living room. (COMFORTABLE)", "comfortable"),
    ],
}

if __name__ == "__main__":
    for k, v in QUIZZES.items():
        n = len(v['questions'])
        per = round(100 / n, 2)
        ai = sum(1 for q in v['questions'] if q['needs_ai'])
        ctx = sum(1 for q in v['questions'] if q['context'])
        print(f"{k}: {v['title']}")
        print(f"  {n} سوال × {per} نمره = 100 | {ai} سوال نیاز به AI | {ctx} سوال context دارن")
